(ns chess.board
  (:require [chess.piece :refer [piece]]))

(def start-position
  (-> {}
      (assoc :a1 (piece :white :rook))
      (assoc :b1 (piece :white :knight))
      (assoc :c1 (piece :white :bishop))
      (assoc :d1 (piece :white :queen))
      (assoc :e1 (piece :white :king))
      (assoc :f1 (piece :white :bishop))
      (assoc :g1 (piece :white :knight))
      (assoc :h1 (piece :white :rook))
      (assoc :a2 (piece :white :pawn))
      (assoc :b2 (piece :white :pawn))
      (assoc :c2 (piece :white :pawn))
      (assoc :d2 (piece :white :pawn))
      (assoc :e2 (piece :white :pawn))
      (assoc :f2 (piece :white :pawn))
      (assoc :g2 (piece :white :pawn))
      (assoc :h2 (piece :white :pawn))
      (assoc :a8 (piece :black :rook))
      (assoc :b8 (piece :black :knight))
      (assoc :c8 (piece :black :bishop))
      (assoc :d8 (piece :black :queen))
      (assoc :e8 (piece :black :king))
      (assoc :f8 (piece :black :bishop))
      (assoc :g8 (piece :black :knight))
      (assoc :h8 (piece :black :rook))
      (assoc :a7 (piece :black :pawn))
      (assoc :b7 (piece :black :pawn))
      (assoc :c7 (piece :black :pawn))
      (assoc :d7 (piece :black :pawn))
      (assoc :e7 (piece :black :pawn))
      (assoc :f7 (piece :black :pawn))
      (assoc :g7 (piece :black :pawn))
      (assoc :h7 (piece :black :pawn))))

(def only-pawns
  (-> {}
      (assoc :a2 (piece :white :pawn))
      (assoc :b2 (piece :white :pawn))
      (assoc :c2 (piece :white :pawn))
      (assoc :d2 (piece :white :pawn))
      (assoc :e2 (piece :white :pawn))
      (assoc :f2 (piece :white :pawn))
      (assoc :g2 (piece :white :pawn))
      (assoc :h2 (piece :white :pawn))
      (assoc :a7 (piece :black :pawn))
      (assoc :b7 (piece :black :pawn))
      (assoc :c7 (piece :black :pawn))
      (assoc :d7 (piece :black :pawn))
      (assoc :e7 (piece :black :pawn))
      (assoc :f7 (piece :black :pawn))
      (assoc :g7 (piece :black :pawn))
      (assoc :h7 (piece :black :pawn))
      (assoc :e1 (piece :white :king))
      (assoc :e8 (piece :black :king))))
